CORE_HOMEVOLUMES=(
  "home/${REAL_USER}/.mozilla"
  "home/${REAL_USER}/.thunderbird"
  "home/${REAL_USER}/.gnupg"
  "home/${REAL_USER}/.ssh"
  "home/${REAL_USER}/.cache"
)

OPTIONAL_HOMEVOLUMES=(
    # Chromium browser profile
    "home/${REAL_USER}/.config/google-chrome"

    # Falkon browser profile
    "home/${REAL_USER}/.config/falkon"

    # Flatpak runtimes and installed applications
    "home/${REAL_USER}/.local/share/flatpak"

    # Flatpak application data (Steam, Firefox, LibreOffice, etc.)
    "home/${REAL_USER}/.var/app"

    # Legacy native Steam installation
    # "home/${REAL_USER}/.local/share/Steam"

    # Rootless Podman containers
    # "home/${REAL_USER}/.local/share/containers"

    # Workflow directories
    # "home/${REAL_USER}/Public"
    # "home/${REAL_USER}/temp"
    # "home/${REAL_USER}/Downloads/temp"
    # "home/${REAL_USER}/Backups"
    # "home/${REAL_USER}/.quickemu"

    # Convenience
    # "home/${REAL_USER}/.local/share/Trash"
)
