CORE_ROOTVOLUMES=(
  "srv"
  "var/cache"
  "var/crash"
  "var/log"
  "var/spool"
  "var/tmp"
)

OPTIONAL_ROOTVOLUMES=(
  "root"
  "var/lib/bootprep"
  "var/lib/flatpak"
  "var/lib/libvirt/images"
  "var/lib/machines"
  "var/lib/sddm"
  "var/opt"
  "var/www"

  # Vendor / third-party software
  # "opt"

  # Container engines
  # "var/lib/docker"
  # "var/lib/podman"

  # Database storage
  # "var/lib/postgresql"
  # "var/lib/mysql"
)
